name: Download and Commit

on:
  schedule:
    - cron: "23 */2 * * *"
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install requests library
        run: |
          pip install -r requirements.txt

      - name: Set Environment Variables
        env:
          NUMIP: ${{ secrets.NUMIP }}
          TOKEN: ${{ secrets.TOKEN }}
          DB_URL: ${{ secrets.DB_URL }}
          FOFA_URL: ${{ secrets.FOFA_URL }}
          RSS_URL: ${{ secrets.RSS_URL }}
        run: |
          echo "NUMIP=${NUMIP}" >> $GITHUB_ENV
          echo "TOKEN=${TOKEN}" >> $GITHUB_ENV
          echo "DB_URL=${DB_URL}" >> $GITHUB_ENV
          echo "FOFA_URL=${FOFA_URL}" >> $GITHUB_ENV
          echo "RSS_URL=${RSS_URL}" >> $GITHUB_ENV

      - name: Download File
        run: python main.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated file on $(date "+%Y/%m/%d %H:%M:%S")"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}.git
          git push
